### ISSUE TITLE
Add a visible flag

### ISSUE THREAD

**Issue by shinrichs** [Servoy/svyPDFViewer#12]
Can you add a visible flag to the PDF Viewer, please? 

Because we show the PDF Viewer with the Table Component in one screen, so if a record hasn't a pdf document behind, we don't want to show the PDF Viewer...

**Comment by pruhsert** [comment]
I see a visible property in designer and in the API. Don't you have that?

**Comment by shinrichs** [comment]
Oh sorry, my fault. We hadn't imported the actual version of PDFViewer webcomponent. 

Yes, you're right Patrick, there's a visible flag in the source code here on GitHub. Thanks!

**Comment by shinrichs** [comment]
We found out that we use the old version of svyPDFViewer without visible flag because the version here on GitHub isn't downloadable over the Web Package Manager in Servoy (check in 8.1.4 and 8.2.1). And mainly we use the Web Package Manager in Servoy to download and update webcomponents not GitHub.
