### ISSUE TITLE
Explore a convenience method to just accept bytes

### ISSUE THREAD

**Issue by seanthomasdevlin** [Servoy/svyPDFViewer#17]
Explore a way to just set bytes on the component. (under the hood it may involve writing the file on the server and getting the URL, but the dev-ex will be easier)
i.e.
`elements.viewer.setBytes(byteArray)`

**Comment by rvanveen-servoy** [comment]
Hi,
* Added support for dataprovider.
* Marked documentURL as deprecated, using a dataprovider will be easier and faster.
* While refactoring also added watches on some properties (zoom, page, noCache)

Internal case number: SVY-14952
