### ISSUE TITLE
CSS clash

### ISSUE THREAD

**Issue by SteveHawes** [Servoy/svyPDFViewer#7]
I have included this component in my project but am not using yet, however the CSS is causing issues with other elements in the project.

Not sure why the CSS is being loaded when the component is not being used on the form and why the CSS has selectors for '*' and 'body' rather than targeting the component specifically.

**Comment by seanthomasdevlin** [comment]
Hi Steve,
What sorts of problems to you see in other elements ?
That should apply to the iFrame. Any padding or body styling you apply will override this I think

**Comment by SteveHawes** [comment]
The way I spotted this is because I use an unordered list in a plugins.dialogs.showInfoDialog(). If the PDFViewer is included in the solution the list items all lose the default padding added by the browser agent stylesheet. This happens even though I have not used the PDFViewer component anywhere in my solution, it is simply included as an NG component. I have attached a sample solution that demonstrates the problem.

If you run the solution and click the Info Dialog button everything looks fine. If you then install the PDFViewer package via the Web Package Manager and do nothing else other than refresh the page and click the button again the list items are all out of alignment and the body of the page has changed.

This happens on both Safari and Chrome on my development machine.

[DialogIssue_SVY10771.servoy.zip](https://github.com/Servoy/svyPDFViewer/files/704525/DialogIssue_SVY10771.servoy.zip)

**Comment by seanthomasdevlin** [comment]
Two workarounds I can think of:

1. Add the selector for **li** tag to your solution's css file to restore the padding that you want.
2. Run the component from source and remove the offending selectors from the viewer's css file

For now, I hesitate to update the viewer's css file in the component distribution unless it really interferes w/ default client

**Comment by SteveHawes** [comment]
I understand the hesitation to change things but the attached project was a single form, totally vanilla Servoy CSS (no custom CSS file) and neither the form nor the solution actually used the PDFViewer (it was simply included as a component). This raises two issues:

1. The component is interfering with the default Servoy client (even when not being used)
2. Why is the CSS being delivered to the client if the component is not being used?

Number 2 is particularly concerning as if I have 100 custom components in my solution then all their CSS is going to be sent to the client for every form in my solution, whether the CSS is used/relevant or not. Should this be raised as a ticket in JIRA?

**Comment by jcompagner** [comment]
about point 2: thats only in the developer, there we load all components (we don't know when there are used or not can be at any point later on)

If you create a WAR and export that then if you dont use it at all in your solution it won't be exported so it won't be loaded in the client,.
But if you do use it somewhere and it is exported then it will be loaded directly at the beginning just as in the developer.

**Comment by SteveHawes** [comment]
OK - I didn't realise that was how it worked. 

Slight exaggeration but if my solution had a single form that used 50 different components and 50 forms that used only the standard Servoy components then the performance of the majority of the application would be impacted by what is needed by the single form. Is there not a way to get Servoy to only send the CSS that is required for the form that is currently displayed? Does this also apply to the JS files?

**Comment by jcompagner** [comment]
this is not how it works, its a single page application (like all angular apps)
The thing is if we only added css when needed, then bugs would still popup but then at places and times that people don't at first understand, 

"my form X works fine if i test it but when my customer does it it goes wrong"

and that is then because the customer followed another path to that form X so that suddenly more css was loaded in. (the customer loaded also a form A first where that component with that css was touched)

Besides that servoy when exporting to a WAR tries to group stuff so that all css are loaded in 1 go from the server.
